spring:
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      group-id: kafka.comsumer.group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer